---
- name: DevOps Engineer MacBook Setup
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:
    - name: Install Homebrew packages
      homebrew:
        name:
          - git
          - python
          - ansible-lint
        state: present

    - name: Install Homebrew Cask packages
      homebrew_cask:
        name:
          - visual-studio-code
          - docker
          - iterm2
          - 1password
          - slack
          - google-chrome
        state: present

    - name: Check installed Visual Studio Code extensions
      shell: "code --list-extensions"
      register: installed_extensions   

    - name: Install Visual Studio Code extensions
      shell: "code --install-extension {{ item }}"
      with_items:
        - hashicorp.terraform
        - github.copilot
        - ms-azuretools.vscode-docker
        - rebornix.ruby
        - wingrunr21.vscode-ruby
        - castwide.solargraph
        - streetsidesoftware.code-spell-checker
      when: item not in installed_extensions.stdout_lines

    - name: Configure .zshrc file
      copy:
        content: |
          # Set the default editor to Vim
          export EDITOR=vim

          # Add some useful aliases
          alias ll='ls -alF'
          alias grep='grep --color=auto'

          # Load Oh My Zsh plugins
          plugins=(git zsh-syntax-highlighting)

          # Set the Oh My Zsh theme
          ZSH_THEME="robbyrussell"

          # Set the default language to English
          export LANG=en_US.UTF-8

          # Store 1000 commands in the history
          HISTSIZE=1000

          # Ignore duplicate commands
          HISTCONTROL=ignoreboth
        dest: "~/.zshrc"
        backup: yes
        mode: 0644


    # - name: Remove Visual Studio Code extensions
    #   shell: "code --uninstall-extension {{ item }}"
    #   with_items:
    #     - ms-vscode.Go
    #   when: item in installed_extensions.stdout_lines

    - name: Add SSH key to GitHub
      shell: "cat ~/.ssh/id_rsa.pub | pbcopy"
      register: ssh_key
      ignore_errors: true

    - name: Show SSH key
      debug:
        msg: "Copy the following SSH key and add it to your GitHub account: {{ ssh_key.stdout }}"
      when: ssh_key is defined and ssh_key.rc == 0

    - name: Clone Git repository
      git:
        repo: 'https://github.com/tomroth/mac-devops-setup.git'
        dest: '~/code/mac-devops-setup'
        update: true
      ignore_errors: true
      register: git_clone

    - name: Push latest changes to the remote repository
      shell: |
        cd ~/code/mac-devops-setup
        git add .
        git commit -m "Update code from MacBook Setup playbook"
        git push
      ignore_errors: true
      